package: yform_quick_edit
version: "1.0.0"
name: YForm QuickEdit
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yform_quick_edit

requires:
    redaxo: ^5.12.0
    php:
        version: '>=7.1'

installer_ignore:
  - node_modules
  - .git
  - .gitignore
  - .gitignore
  - package.json
  - yarn.lock
  - resources
