package: yform_quick_edit
version: "0.0.1-dev"
name: YForm QuickEdit
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yform_quick_edit

requires:
    redaxo: ^5.12.0
    php:
        version: '>=7.1'
